### PR TITLE
Activate directions link

### PR DESCRIPTION
**Pull request by FlipperPA**
Activate directions link in left nav, and disable the button in the pop-up until we can figure out why it isn't working.

I can't figure out why the directions button on the pop-up isn't working. I've tried it both as a `<button>` and an `<a>` tag. More investigation is needed. In the meantime, this activates the `Directions` link in the left navigation using the same form as the current meeting guide.

### CODE REVIEW

**Comment by FlipperPA** [comment]
@joshreisner - I meant to tag you in this one for the question about the pop-up.

**Comment by joshreisner** [comment]
I'm guessing the problem with the button in the infowindow is some kind of mapbox onclick handler. Anyway fine to hide that for now.

Question: on iOS does this take you to the Apple Maps app? I'm guessing no, and I think you can achieve that by switching the domain in your link to maps.apple.com, and keeping the rest the same. This should redirect to google on Android.

https://developer.apple.com/library/archive/featuredarticles/iPhoneURLScheme_Reference/MapLinks/MapLinks.html

Aside from that, just run a `npm run prod` and we should be good to go 👍

**Comment by FlipperPA** [comment]
On iPhone, it takes me to Google Maps, and if it isn't installed, I assume it'll take me to Apple Maps within Safari.

Do we want to make anyone suffer with Apple Maps? :) It's a truly wretched product! We can decide tomorrow, it's an easy fix.

**Comment by joshreisner** [comment]
Yeah we definitely want it to go to the Apple Maps app. It's a million times better than going to a website.

**Pull request merged**
