### PR TITLE
Adds "Near Me" Geolocation Mode to the Search Drop Down

### PR DESCRIPTION
**Pull request by FlipperPA**
This is an initial attempt to request the end user's location on load, and calculate the distance in miles to the meeting. If the user accepts, it will calculate the distance to the first meeting in the array and dump the results to the console.

@joshreisner, what do you think of this approach? My hope was simply to display the distance to each meeting with the address, if the user allows their location to be probed. After talking with our tech advisory group here in Philly, that seems to be the main concern for folks from out of town.

### CODE REVIEW

**Comment by joshreisner** [comment]
Hey @FlipperPA the current WP plugin has three "modes" : Search, Near Location, and Near Me. Only in the "Near Me" mode does it request user geo and show the distance column. You're able to link directly to the "Near Me" mode from the site. Doesn't look like Philadelphia is doing this but most other sites do. I'm open to making a UI change but that'd be separate conversation.

If the goal of this branch is to implement the "Near Me" mode as it works in the plugin that'd be awesome! 

Running the branch locally I'm not actually seeing the new column. Do you know what the issue might be?

**Comment by FlipperPA** [comment]
@joshreisner I was taking a slightly different approach, and requesting the user's location while in the standard search mode. In testing, I'm able to Geocode our 1,765 meetings in 134 milliseconds, so it really isn't that big a hit.

I hadn't fully implemented the distance yet, but let me finish what I'm thinking and then you'll be able to see it. Thanks!

**Comment by joshreisner** [comment]
It's not a question of processing time, it's a question of authorization and user expectations. I don't want the default view to immediately ask the user for their location before rendering the page. I'd prefer they opt in to sharing it, either by clicking a link like "show meetings near me" or selecting an interface element from the top (right now that's "near me" in the dropdown but could be made more prominent)

If the request is immediate, people are going to be more inclined to deny it, and once they've done that, it's pretty much game over. I think only a very slim minority of people are going to go in and re-authorize location sharing.

**Comment by FlipperPA** [comment]
Fair enough! I'll pivot. Does the code for calculating distance and such look okay? It seems to match up well with the tests I've done at home, but I must admit, my trigonometry is very out of practice. :)

**Comment by FlipperPA** [comment]
@joshreisner I think this is close to ready to go. Feel free to break out the red pen if you have suggestions on improving anything, as I'm still new to ReactJS. This has been refactored to use the "Near Me" in the dropdown.

**Comment by FlipperPA** [comment]
@joshreisner PS: you asked earlier about the column not showing up; I've made a modification here to allow "Near Me" mode to show up with local development: https://github.com/code4recovery/react/blob/feature/user-location/src/helpers/data.jsx#L320

**Comment by joshreisner** [comment]
awesome thanks @FlipperPA ! i promise to review this soon and let you know

**Comment by joshreisner** [comment]
Hey @FlipperPA so this works really well in testing, but there are a few things I think we want to take care of before we merge this.

1. architecturally, i don't think the filtering belongs in the Controls component, probably it'd be better to move it to the Data helper
1. it's great to check for `navigator.geolocation` but we should probably do that when we're setting `capabilities.geolocation` since that's the intent of that var
1. the existing "near me" functionality doesn't simply display distances to the user, it also filters by distance. I think the default is 5 miles, but a new dropdown is exposed in place of the Region / District dropdown with like 1, 2, 5, 10, etc.
1. we should hide the distance column again if they switch modes
1. extremely minor, but we should use `const` and `let` instead of `var`
1. we should try to make the distance more prominent on mobile (the main use-case) like it is in the plugin

Sorry this sounds like a lot of stuff! I'm happy to merge if we can take care of 1 and 2. The rest of the stuff can be deferred for later.

**Comment by FlipperPA** [comment]
Thanks for the feedback, @joshreisner! I'll be getting back to this in a day or two, as we've just pushed out the new version of our website. You might be interested in seeing this in action: https://www.aasepia.org

:)

**Comment by FlipperPA** [comment]
@joshreisner I've amended this PR to take care of (1) & (5).

However, I have a questions about (2). The reason for having the `navigator.geolocation` where I do is that prompts the end user to allow their location to be used. It triggers after they set their mode to "Near Me."

If we were to trigger the request when setting the `capabilities.geolocation` variable, it would ask them to allow us to use their location before changing their mode to `Near Me`, which was what I refactored away from, right? Or am I missing something?

I'll add Issues for (3), (4), and (6), so they don't fall through the cracks moving forward.

I hope you're having a lovely holiday season, brother!

**Comment by joshreisner** [comment]
@FlipperPA `navigator.geolocation` just checks for the existence of the object; you have to run `getCurrentPosition` (or better yet probably `watchPosition` for mobile users) to actually pop the request. https://codepen.io/joshreisner/pen/xxbLPEK

Nice job on the site. I updated your API URL in the app so it's pulling from the new data source now.

**Comment by joshreisner** [comment]
I see the refactor to move the function, but I'm talking about actually moving the filtering. Let me approach it from a different angle:

See how in your dev environment if you switch the day to Tuesday the URL changes to https://react.test/?day=2 and then if you reload the page then Tuesday is still set? This is important functionality because it lets you permalink to Tuesday.

Similarly, when you set the mode to "Near Me" then the URL changes to https://react.test/?mode=me -- but if you reload it's no longer geolocating. This is because the trigger to geolocate is currently inside the control so you need to click or tap to make it go. 

Instead we should remove lines 131-135 from `controls.setMode` and do all this navigator stuff inside `data.filterMeetingData` at about line 37, (probably make it an `else` condition on keyword search).

Hopefully that makes sense? If not lmk, I'm happy to do a zoom. I don't think it will take much more work, it seems very close…

**Comment by joshreisner** [comment]
Also before I forget, did you want to make 'near me' the default? Because you should be able to do that with this change, and by adding `mode: 'me'` to your `config.defaults`

```
        defaults: {
            title: true,
            mode: 'me', //add me to make the geo happen automatically
        },
```

**Comment by FlipperPA** [comment]
AHA, that absolutely makes sense. I think I'll take you up on an hour on video, if that's cool, just so we can get some of this pushed across the finish line without going back and forth. My goal here is to get good enough with ReactJS to help the next person who wants to contribute!

**Comment by joshreisner** [comment]
Hey @FlipperPA ok lmk what you think of the state of it now. The main thing is: `filterMeetingData` runs at each render, but we will get a render a) when you change modes, and b) when the `getCurrentPosition` callback fires. So there's an if statement in `filterMeetingData` that says do we have a center? If not, ask for current position. If so, then do the filtering (although we're not there yet).

Distances are updated or cleared on each render,

This should actually close #38 -- this is happening now in `table.jsx`.

Also this should satisfy or get pretty close to #39 as well.

**Comment by joshreisner** [comment]
Question: should we be storing the `center` in the query string? It is currently. I could see that as a privacy concern, but also possibly a support win, if someone is able to share what they're seeing in terms of distances.

Related: are we getting too much precision on the geo? Maybe we should limit it to 3 or 4 decimal places? https://www.google.com/search?q=geo+coordinate+precision

**Comment by FlipperPA** [comment]
@joshreisner I took at look at this, and I think we're getting close. I think we may just need some refinement on passing the URL parameters around depending on the mode.

If I come to the site, and search for `bucks county`, it gives me what I expect:
image

If I then switch mode to `Near Me`, and `Allow Location Access`, it reverts to the full meeting list without the search term (I believe this is as designed), and adds the distance:
image

Then, if I switch back to search, it doesn't re-apply the search I had done:
image

Of course, this might be something we need to add when we put the distance filter in place.

**Comment by joshreisner** [comment]
Yeah, I don't think we want to preserve the search terms.

**Pull request merged**
