### PR TITLE
Add 'Back to Meetings' link to mirror the TSML plugin functionality.

### PR DESCRIPTION
**Pull request by FlipperPA**
Here's a hopefully easy one for review, @joshreisner :)

### CODE REVIEW

**Comment by joshreisner** [comment]
Hm, I don't like it yet visually. It adds a redundant link and an opposing arrow, which is confusing. The tap target it pretty small for a navigation element. And it doesn't address the core frustration, which is the broken back button.

I think we have to keep thinking about this one.

Screen Shot 2020-02-01 at 2 41 57 PM

**Comment by FlipperPA** [comment]
Sounds good to me. I'll switch it up to the same treatment as here, just so we're at the same approximate treatment as we were before:

image

I tried the reverse arrow just to try something new. :)

**Comment by joshreisner** [comment]
@FlipperPA ok I'm sensing you want to get a change through so I addressed my visual concerns by removing the redundant link and adding a border. I think it maybe looks slightly worse on desktop but slightly better on mobile so it's fine.

I don't think users are going to be happy until the back button functionality (aka swiping to go back) is working, but that does look like a heavier lift.

Anyway if you're ok with this feel free to close & merge. Let's either leave the issue open or create a new one for the back button.

**Comment by FlipperPA** [comment]
My apologies @joshreisner - I didn't mean to pressure you at all! I'm able to pull individual branches into the `integration/sepia` branch as a sort of alpha for my needs in the meantime, so please, don't ever rush through something on my account! I do appreciate it, however. :) I will take a look now. You've got a better eye for this stuff than me!

**Pull request merged**
